### ISSUE TITLE
Add SolutionDir xbuild parameter (or ability to define custom parameters)

### ISSUE THREAD

**Issue by Dids** [voydz/souyuz#5] opened 2017-03-04 13:33 UTC
In my particular case, I need xbuild to have `/p:SolutionDir` defined, so that Realm will compile for Android:
https://github.com/realm/realm-dotnet/issues/656

**EDIT:** My temporary fix is to add a shell script to my Fastfile, then inside the shell script run the xbuild command, adding `/p:SolutionDir=$(pwd)/..` to the command. Hope this is easy to fix/implement in souyuz.

**Comment by voydz** [comment] 2017-03-13 11:57
Hi, I will have a look into this. Thanks for your feedback.

**Comment by voydz** [comment] 2017-03-30 13:26
As I am currently lacking time, I am more than happy to receive pull requests for this. 😄

**Comment by Dids** [comment] 2017-04-03 14:17
Oh wow, thank you @johannesberdin for the PR! I'm not as familiar with Ruby, so didn't look into yet.
Hope you can get it merged soon @voydz. :)

**Comment by voydz** [comment] 2017-04-03 19:25
@Dids I just released 0.6.5 containing this changes. Could you try and report whether the problem is fixed for you, or not?

Thanks again to @johannesberdin for the pull request. 🎉

**Comment by Dids** [comment] 2017-04-03 19:36
@voydz Just tested it and can confirm it works!

**Comment by Dids** [comment] 2017-04-18 18:37
The PR fixed the original issue, but unfortunately caused another one.

When compiling in Xamarin Studio, `SolutionDir` includes a forward flash, so when used it expands to this: `$(SolutionDir)/Longer/Path/Here`.
When building directly with xbuild, the trailing slash is *not* added automatically, resulting in this: `$(SolutionDir)Longer/Path/Here`, which ends up creating a new folder above the solution directory.

@voydz I'll submit a PR in a sec, since this should be easy to fix with no repercussions (that I can think of).

**Comment by Dids** [comment] 2017-04-18 18:47
@voydz PR submitted. It's literally just adding a single character (forward slash).

**Comment by voydz** [comment] 2017-04-18 18:54
@Dids thank you for this, would you mind adding a little comment and references, on how this is a workaround to fix xbuild not automatically adding a trailing slash to it?

**Comment by Dids** [comment] 2017-04-18 19:10
@voydz Added more details to the PR.

**Comment by voydz** [comment] 2017-04-18 19:14
@Dids Thanks, looking forward to release a new version tomorrow morning. Closing again, since everything should be working now.

If further problems appear, feel free to reopen.

**Closed as completed by voydz** 2017-04-18 19:14 UTC
Labels: enhancement, help wanted
